name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Fix go.mod version
      run: |
        sed -i 's/go 1.24.1/go 1.20/' go.mod

    - name: Install UPX
      run: sudo apt-get update && sudo apt-get install -y upx-ucl

    - name: Manage dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Execute build script
      run: chmod +x build.sh && ./build.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: build/

    - name: Generate SHA256 checksums
      run: |
        cd build/
        find . -type f -exec sha256sum {} \; > checksums.txt

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*
        generate_release_notes: true 